### ISSUE TITLE
Domain Analizi

### ISSUE THREAD

**Issue by cantahmazoglu** [cantahmazoglu/BBM487-20142-7#3]
Domain analizi yaparak, bu alanla ilgili class’ları ve ilişkileri UML Class Diyagram kullanarak gösteriniz. Aynı diyagram üzerinde veri gereksinimlerini classların attribute’ları olarak belirtiniz.

**Comment by melizersoy** [comment]
UML Class Diyagramı kullanılarak ilgili classlar ve ilişkiler gösterildi. Veri gereksinimleri classların attribute'ü olarak gösterildi.
